In [22]:
x = open("aoc6.txt") do f
    [x for x in eachline(f)]
    end;

In [23]:
x1=[tuple(parse.(Int, split(x,","))...) for x in x]

50-element Array{Tuple{Int64,Int64},1}:
 (135, 127)
 (251, 77) 
 (136, 244)
 (123, 169)
 (253, 257)
 (359, 309)
 (100, 247)
 (191, 323)
 (129, 323)
 (76, 284) 
 (69, 56)  
 (229, 266)
 (74, 216) 
 ⋮         
 (103, 274)
 (357, 144)
 (314, 118)
 (67, 196) 
 (156, 265)
 (254, 357)
 (218, 271)
 (118, 94) 
 (300, 189)
 (290, 356)
 (354, 91) 
 (209, 334)

In [24]:
rlim = maximum(x->x[1], x1)

359

In [25]:
clim = maximum(x->x[2], x1)
rclim = max(rlim+1, clim+1)

360

In [26]:
minimum(x->x[1], x1)

60

In [27]:
minimum(x->x[2], x1)

51

In [28]:
# create a distance to every pont there
grid = zeros(Int, rclim,rclim);
grid .= -1;

In [29]:
function dist2pt!(grid,r,c,x1)
    mandist = [abs(r-1-x1[2]) + abs(c-1-x1[1]) for x1 in x1]
    minmandist = minimum(mandist)
    res = findall(mandist .== minmandist)
    #println(x1[res])
    if length(res) == 1
      grid[r,c] = res[1][1]
    end
    grid
end

dist2pt! (generic function with 1 method)

In [176]:
for r in 1:rclim
    for c in 1:rclim
        grid = dist2pt!(grid, r,c, x1)
    end
end

In [30]:
grid = Array{Int}(undef, rclim, rclim)
grid .= 0

360×360 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  

In [31]:
function dist2pt2!(grid,r,c,x1)
    mandist = [abs(r-1-x1[2]) + abs(c-1-x1[1]) for x1 in x1]
    grid[r,c] = sum(mandist)
    grid
end

dist2pt2! (generic function with 1 method)

In [32]:
for r in 1:rclim
    for c in 1:rclim
        grid = dist2pt2!(grid, r,c, x1)
    end
end

In [33]:
sum(grid .< 10000)

38670

In [21]:
grid

10×10 Array{Int64,2}:
 54  48  46  44  44  44  46  48  50  56
 48  42  40  38  38  38  40  42  44  50
 44  38  36  34  34  34  36  38  40  46
 40  34  32  30  30  30  32  34  36  42
 38  32  30  28  28  28  30  32  34  40
 38  32  30  28  28  28  30  32  34  40
 40  34  32  30  30  30  32  34  36  42
 44  38  36  34  34  34  36  38  40  46
 48  42  40  38  38  38  40  42  44  50
 52  46  44  42  42  42  44  46  48  54

In [178]:
okelems=setdiff(1:length(x1), setdiff(vcat(
    grid[1,:], 
    grid[end,:],
    grid[:,1],
            grid[:,end]) |> unique,-1))

28-element Array{Int64,1}:
  3
  4
  5
  8
  9
 12
 14
 15
 16
 17
 18
 22
 23
  ⋮
 29
 30
 31
 33
 36
 37
 38
 39
 41
 43
 45
 47

In [179]:
using StatsBase
okcnt = countmap(vec(grid))

sort([(oke,okcnt[oke]) for oke in okelems], by =x->x[2])

28-element Array{Tuple{Int64,Int64},1}:
 (37, 286) 
 (23, 352) 
 (4, 378)  
 (8, 502)  
 (29, 831) 
 (17, 927) 
 (22, 1104)
 (12, 1126)
 (36, 1159)
 (16, 1192)
 (24, 1212)
 (41, 1245)
 (31, 1346)
 ⋮         
 (38, 2065)
 (30, 2095)
 (15, 2218)
 (43, 2226)
 (25, 2322)
 (45, 2580)
 (5, 2896) 
 (26, 2944)
 (3, 3145) 
 (33, 3705)
 (14, 5794)
 (47, 5975)

In [167]:
mandist = [abs(r-1-x1[1]) + abs(c-1-x1[2]) for x1 in x1]

6-element Array{Int64,1}:
  5
  2
 10
  4
  5
 12

In [121]:
    minmandist = minimum(mandist)
x1

6-element Array{Tuple{Int64,Int64},1}:
 (1, 1)
 (1, 6)
 (8, 3)
 (3, 4)
 (5, 5)
 (8, 9)

In [114]:
    res = findall(mandist .== minmandist)
    #println(x1[res])
    if length(res) == 1
      grid[r,c] = res[1][1]
    end
    grid

9×10 Array{Int64,2}:
  1   1  1  1  -1   2   2   2   2   2
  1   1  1  1  -1   2   2   2   2   2
  1   1  1  4   4  -1   2   2   2   2
  1   1  4  4   4   4  -1  -1  -1  -1
  1   1  4  4   4   5   5   5   5   6
 -1  -1  5  5   5   5   5   5   5   6
  3   3  3  3   5   5   5   5   6   6
  3   3  3  3   3   5   5   6   6   6
  3   3  3  3   3   3  -1   6   6   6

In [122]:
grid

9×10 Array{Int64,2}:
  1   1  1  1  -1   2   2   2   2   2
  1   1  1  1  -1   2   2   2   2   2
  1   1  1  4   4  -1   2   2   2   2
  1   1  4  4   4   4  -1  -1  -1  -1
  1   1  4  4   4   5   5   5   5   6
 -1  -1  5  5   5   5   5   5   5   6
  3   3  3  3   5   5   5   5   6   6
  3   3  3  3   3   5   5   6   6   6
  3   3  3  3   3   3  -1   6   6   6